## PROD
spring:
  config:
    activate:
      on-profile: "db-prd"
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: {url}
    username: {your-user}
    password: {your-pass}
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show-sql: true
        format_sql: true