
# ** DataBase  **
## LOCAL
spring:
  config:
    activate:
      on-profile: "db-loc"
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: {url}
    username: {user}
    password: {pass}
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show-sql: true       #console 옵션
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect

---

## PROD
spring:
  config:
    activate:
      on-profile: "db-prd"
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: {url}
    username: {user}
    password: {pass}
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show-sql: true       #console 옵션
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect