spring:
  config:
    import:
      - classpath:/config/config-common.yml
      - classpath:/config/config-db.yml
      - classpath:/config/config-logging.yml
  profiles:
    active: loc
    group:
      "loc": "common, logging-cons, db-loc"
      "prd": "common, logging-file, db-prd"